CREATE TABLE MEMBER (
	MEMBER_ID INT PRIMARY KEY,
	MEMBER_NAME VARCHAR(50) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR(255) NOT NULL,
	MEMBER_NICKNAME VARCHAR(50) NOT NULL UNIQUE, /*탈퇴한 회원 (withdraw)의경우는 전부다 "탈퇴한 회원"으로 뜨게 하는 쿼리 추가하기*/
	MEMBER_CASH INT DEFAULT 0 NOT NULL,
	MEMBER_ROLE VARCHAR(10) DEFAULT 'ACTIVE' NOT NULL, /* ENUM 을 빼서 타입이 비게 되어 VARCHAR로 문자열인 등급을 받아옴 */
	MEMBER_PROFILE_IMAGE CLOB DEFAULT NULL, /* URL */
	MEMBER_EMAIL VARCHAR(255) NOT NULL UNIQUE,
	MEMBER_PHONE_NUMBER VARCHAR(255) NULL UNIQUE,
	
	CONSTRAINT MEMBER_ROLE_CHK
		CHECK (MEMBER_ROLE IN ('ACTIVE','WITHDRAWN','ADMIN'))
);

CREATE SEQUENCE MEMBER_ID_SEQ  /* MEMBER_ID 시퀀스로 4부터 1씩 증가 */
	START WITH 4
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;
=====================================================================
-- 회원 가입 - 회원 INSERT
INSERT INTO MEMBER (
	MEMBER_ID,
	MEMBER_NAME,
	MEMBER_PASSWORD,
	MEMBER_NICKNAME,
	MEMBER_CASH,
	MEMBER_ROLE,
	MEMBER_PROFILE_IMAGE,
	MEMBER_EMAIL,
	MEMBER_PHONE_NUMBER
) VALUES ( --초기값에서 CASH > 0, ROLE > ACTIVE, IMAGE > NULL, PHONE_NUMBER > NULL
	MEMBER_ID_SEQ.NEXTVAL,'김유진','animale1!','김유신장군',0,'ACTIVE',NULL,'qwer@naver.com',NULL 
);

INSERT INTO MEMBER (
  MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_NICKNAME,
  MEMBER_CASH, MEMBER_ROLE, MEMBER_PROFILE_IMAGE, MEMBER_EMAIL, MEMBER_PHONE_NUMBER
) VALUES (
  MEMBER_ID_SEQ.NEXTVAL,'박민준','animale1!','박치기민준',0,'ACTIVE',NULL,'minjun.park01@naver.com',NULL
);

INSERT INTO MEMBER (
  MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_NICKNAME,
  MEMBER_CASH, MEMBER_ROLE, MEMBER_PROFILE_IMAGE, MEMBER_EMAIL, MEMBER_PHONE_NUMBER
) VALUES (
  MEMBER_ID_SEQ.NEXTVAL,'이서연','animale1!','서연이짱',0,'ACTIVE',NULL,'seoyeon.lee02@naver.com',NULL
);

INSERT INTO MEMBER (
  MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_NICKNAME,
  MEMBER_CASH, MEMBER_ROLE, MEMBER_PROFILE_IMAGE, MEMBER_EMAIL, MEMBER_PHONE_NUMBER
) VALUES (
  MEMBER_ID_SEQ.NEXTVAL,'최지훈','animale1!','지훈펀치',0,'ACTIVE',NULL,'jihoon.choi03@naver.com',NULL
);

INSERT INTO MEMBER (
  MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_NICKNAME,
  MEMBER_CASH, MEMBER_ROLE, MEMBER_PROFILE_IMAGE, MEMBER_EMAIL, MEMBER_PHONE_NUMBER
) VALUES (
  MEMBER_ID_SEQ.NEXTVAL,'정하늘','animale1!','하늘바람',0,'ACTIVE',NULL,'haneul.jung04@naver.com',NULL
);

INSERT INTO MEMBER (
  MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_NICKNAME,
  MEMBER_CASH, MEMBER_ROLE, MEMBER_PROFILE_IMAGE, MEMBER_EMAIL, MEMBER_PHONE_NUMBER
) VALUES (
  MEMBER_ID_SEQ.NEXTVAL,'윤도현','animale1!','도현이형',0,'ACTIVE',NULL,'dohyun.yoon05@naver.com',NULL
);

INSERT INTO MEMBER (
  MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_NICKNAME,
  MEMBER_CASH, MEMBER_ROLE, MEMBER_PROFILE_IMAGE, MEMBER_EMAIL, MEMBER_PHONE_NUMBER
) VALUES (
  MEMBER_ID_SEQ.NEXTVAL,'한지민','animale1!','지민토끼',0,'ACTIVE',NULL,'jimin.han06@naver.com',NULL
);

INSERT INTO MEMBER (
  MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_NICKNAME,
  MEMBER_CASH, MEMBER_ROLE, MEMBER_PROFILE_IMAGE, MEMBER_EMAIL, MEMBER_PHONE_NUMBER
) VALUES (
  MEMBER_ID_SEQ.NEXTVAL,'강태호','animale1!','태호대장',0,'ACTIVE',NULL,'taeho.kang07@naver.com',NULL
);

INSERT INTO MEMBER (
  MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_NICKNAME,
  MEMBER_CASH, MEMBER_ROLE, MEMBER_PROFILE_IMAGE, MEMBER_EMAIL, MEMBER_PHONE_NUMBER
) VALUES (
  MEMBER_ID_SEQ.NEXTVAL,'오수빈','animale1!','수빈별',0,'ACTIVE',NULL,'subin.oh08@naver.com',NULL
);

INSERT INTO MEMBER (
  MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_NICKNAME,
  MEMBER_CASH, MEMBER_ROLE, MEMBER_PROFILE_IMAGE, MEMBER_EMAIL, MEMBER_PHONE_NUMBER
) VALUES (
  MEMBER_ID_SEQ.NEXTVAL,'임준호','animale1!','준호스나이퍼',0,'ACTIVE',NULL,'junho.lim09@naver.com',NULL
);

-- 회원 가입 중 ID 중복검사
SELECT COUNT(*) CNT FROM MEMBER WHERE MEMBER_NAME = '김유진';
-- 회원 가입 중 닉네임 중복검사
SELECT COUNT(*) CNT FROM MEMBER WHERE MEMBER_NICKNAME = '김유신장군';
=====================================================================
-- 관리자 샘플 계정
INSERT INTO MEMBER (
    MEMBER_ID,
    MEMBER_NAME,
    MEMBER_PASSWORD,
    MEMBER_NICKNAME,
    MEMBER_CASH,
    MEMBER_ROLE,
    MEMBER_PROFILE_IMAGE,
    MEMBER_EMAIL,
    MEMBER_PHONE_NUMBER
) VALUES (
    1, 'admin', '1234', '관리자', 0 , 'ADMIN', NULL , 'admin@site.com', NULL
);
===================================================
-- 로그인 - ID/PW로 회원 조회
SELECT MEMBER_ID,
	MEMBER_NAME,
	MEMBER_PASSWORD,
	MEMBER_NICKNAME,
	MEMBER_CASH,
	MEMBER_ROLE,
	MEMBER_PROFILE_IMAGE,
	MEMBER_EMAIL,
	MEMBER_PHONE_NUMBER
FROM MEMBER 
WHERE MEMBER_NAME = '김유진'
AND MEMBER_PASSWORD = '1234'
AND MEMBER_ROLE IN ('ACTIVE','ADMIN'); -- ACTIVE,관리자 가 아니면 로그인이 안됨
===================================================
-- 마이페이지 - 로그인한 회원 기본 정보 조회
SELECT MEMBER_ID,
	MEMBER_NAME,
	MEMBER_NICKNAME,
	MEMBER_CASH,
	MEMBER_ROLE,
	MEMBER_PROFILE_IMAGE,
	MEMBER_EMAIL,
	MEMBER_PHONE_NUMBER
FROM MEMBER
WHERE MEMBER_ID = '4';  -- 세션에서 꺼낸 MEMBER_ID
===================================================
-- 닉네임 변경
UPDATE MEMBER SET MEMBER_NICKNAME = '김유신장군' WHERE MEMBER_ID = '4';
-- 프로필 이미지 변경
UPDATE MEMBER SET MEMBER_PROFILE_IMAGE = NULL WHERE MEMBER_ID = '4';

-- 비밀번호 변경
-- 현재 비밀번호 확인(본인 검증)
SELECT MEMBER_ID FROM MEMBER WHERE MEMBER_ID = '4' AND MEMBER_PASSWORD = '1234';
-- 비밀번호 변경 
UPDATE MEMBER SET MEMBER_PASSWORD = '3456' WHERE MEMBER_ID = '4';

-- 비밀번호 찾기 - ID 존재 확인
SELECT MEMBER_ID FROM MEMBER WHERE MEMBER_NAME = '김유진';
-- 비밀번호 찾기 - 이메일 가져오기(ID 확인 후)
SELECT MEMBER_EMAIL FROM MEMBER WHERE MEMBER_NAME = '김유진';
=================================================================
-- 캐시 충전 / 차감
-- 캐시 현재값 조회
SELECT MEMBER_CASH FROM MEMBER WHERE MEMBER_ID = '4';

-- 캐시 충전
UPDATE MEMBER SET MEMBER_CASH = MEMBER_CASH + 1000 WHERE MEMBER_ID = 4;
-- 캐시 차감
UPDATE MEMBER SET MEMBER_CASH = MEMBER_CASH - 1000 WHERE MEMBER_ID = 4 AND MEMBER_CASH >= 1000;


-- 회원 탈퇴
UPDATE MEMBER SET MEMBER_ROLE = 'WITHDRAWN' WHERE MEMBER_ID = '4';

DELETE FROM MEMBER WHERE MEMBER_ID = '14';



SELECT * FROM MEMBER;


DROP TABLE MEMBER;

DROP SEQUENCE MEMBER_ID_SEQ /* MEMBER_ID 시퀀스 드랍 */